"""empty message

Revision ID: e49a63ef8205
Revises: 
Create Date: 2017-12-16 17:15:51.350000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e49a63ef8205'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mk_topic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('brief', sa.Text(), nullable=False),
    sa.Column('avatar', sa.String(length=255), nullable=False),
    sa.Column('updatetime', sa.DateTime(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mk_topic_name'), 'mk_topic', ['name'], unique=False)
    op.create_table('mk_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('cover', sa.String(length=255), nullable=True),
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.Column('verification_code', sa.String(length=255), nullable=True),
    sa.Column('verification_code_timestamp', sa.DateTime(), nullable=True),
    sa.Column('updatetime', sa.DateTime(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mk_user_email'), 'mk_user', ['email'], unique=False)
    op.create_index(op.f('ix_mk_user_username'), 'mk_user', ['username'], unique=True)
    op.create_table('mk_article_article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('access', sa.String(length=255), nullable=False),
    sa.Column('markdown', sa.Text(), nullable=False),
    sa.Column('html', sa.Text(), nullable=False),
    sa.Column('updatetime', sa.DateTime(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=False),
    sa.Column('abstract_timestamp', sa.DateTime(), nullable=False),
    sa.Column('cover', sa.String(length=255), nullable=True),
    sa.Column('cover_timestamp', sa.DateTime(), nullable=True),
    sa.Column('pathname', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['mk_user.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mk_user_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sex', sa.Integer(), nullable=False),
    sa.Column('profile', sa.Text(), nullable=False),
    sa.Column('residence', sa.String(length=255), nullable=False),
    sa.Column('profession', sa.String(length=255), nullable=False),
    sa.Column('college', sa.String(length=255), nullable=False),
    sa.Column('major', sa.String(length=255), nullable=False),
    sa.Column('education', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['mk_user.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mk_article_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['mk_article_article.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mk_article_topic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['mk_article_article.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['mk_topic.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mk_article_topic')
    op.drop_table('mk_article_image')
    op.drop_table('mk_user_profile')
    op.drop_table('mk_article_article')
    op.drop_index(op.f('ix_mk_user_username'), table_name='mk_user')
    op.drop_index(op.f('ix_mk_user_email'), table_name='mk_user')
    op.drop_table('mk_user')
    op.drop_index(op.f('ix_mk_topic_name'), table_name='mk_topic')
    op.drop_table('mk_topic')
    # ### end Alembic commands ###
